Update Install-Betterfox

diff --git a/Install-Betterfox b/Install-Betterfox
--- a/Install-Betterfox
+++ b/Install-Betterfox
@@ -8,25 +8,19 @@ if [ "$os" = "Linux" ]; then
     echo "Running on Linux"
     pkill firefox
     directory=$(find ~/.mozilla/firefox/ -type d -name '*default-release*' -print -quit)
-    if [ -n "$directory" ]; then
-        cd "$directory" || exit 1
-        rm -f user.js
-        curl -O https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js
-        pkill firefox
-    else
-        echo "Firefox directory not found."
-    fi
 elif [ "$os" = "Darwin" ]; then
     echo "Running on macOS"
     directory=$(find ~/Library/Application\ Support/Firefox/Profiles -type d -name '*default-release*' -print -quit)
-    if [ -n "$directory" ]; then
-        cd "$directory" || exit 1
-        rm -f user.js
-        curl -O https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js
-        pkill firefox
-    else
-        echo "Firefox directory not found."
-    fi
 else
     echo "Unknown or unsupported operating system"
+    exit 1
+fi
+
+if [ -n "$directory" ]; then
+    cd "$directory" || exit 1
+    rm -f user.js
+    curl -O https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js
+    pkill firefox
+else
+    echo "Firefox directory not found."
 fi
