Update InstallBetterfox

diff --git a/InstallBetterfox b/InstallBetterfox
--- a/InstallBetterfox
+++ b/InstallBetterfox
@@ -1,11 +1,27 @@
 #!/bin/sh
 rm -- "$0"
-directory=$(find ~/Library/Application\ Support/Firefox/Profiles -type d -name '*default-release*' -print -quit)
-if [ -n "$directory" ]; then
-  cd "$directory" || exit 1
-  rm -f user.js
-  curl -O https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js
-  pkill firefox
+
+if [[ "$OSTYPE" == "linux-gnu"* ]]; then
+    echo "Running on Linux"
+    pkill firefox
+    directory=$(find ~/.mozilla/firefox/ -type d -name '*default-release*' -print -quit)
+    if [ -n "$directory" ]; then
+        cd "$directory" || exit 1
+        curl -O https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js
+    else
+        echo "Firefox directory not found."
+    fi
+elif [[ "$OSTYPE" == "darwin"* ]]; then
+    echo "Running on macOS"
+    directory=$(find ~/Library/Application\ Support/Firefox/Profiles -type d -name '*default-release*' -print -quit)
+    if [ -n "$directory" ]; then
+        cd "$directory" || exit 1
+        rm -f user.js
+        curl -O https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js
+        pkill firefox
+    else
+        echo "Firefox directory not found."
+    fi
 else
-  echo "Firefox directory not found."
+    echo "Unknown or unsupported operating system"
 fi
