Update macOS

diff --git a/macOS b/macOS
--- a/macOS
+++ b/macOS
@@ -1,22 +1,13 @@
 #!/bin/sh
 rm -- "$0"
-cd ~/
 
-# Find all directories matching the pattern
-find ~/Library/Application\ Support/Firefox/Profiles -type d -name '*default-release*' | while read -r directory; do
-    if [ -n "$directory" ]; then
-        # Move into the directory
-        cd "$directory" || exit 1
-
-        # Remove existing user.js file
-        rm -f user.js
-
-        # Download the new user.js file
-        curl -O https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js
-
-        # Restart Firefox
-        pkill firefox
-    else
-        echo "Firefox directory not found."
-    fi
-done
+echo "Running on macOS"
+directory=$(find ~/Library/Application\ Support/Firefox/Profiles -type d -name '*default-release*' -print -quit)
+if [ -n "$directory" ]; then
+    cd "$directory" || exit 1
+    rm -f user.js
+    curl -O https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js
+    pkill firefox
+else
+    echo "Firefox directory not found."
+fi
